import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {parse} from 'acorn';
const runtime=fs.readFileSync(new URL('./runtime.mjs',import.meta.url),'utf8');
const context=()=>vm.createContext({Response,Request,Headers,URL,console,setTimeout,clearTimeout,TextEncoder,TextDecoder,AbortSignal,AbortController,fetch:async()=>{throw new Error('Network disabled in tests');}});
async function isolated({current=[],fresh=[],latencies={},sourceFails=false,saveFails=false}={}) {
 let cfg={optimizer:{count:5,threads:2},preferredIPs:structuredClone(current),admin:'retained'};let writes=0;
 const adapter={setEnv(){},load:async()=>structuredClone(cfg),save:async(_e,next)=>{if(saveFails)return false;writes++;cfg=structuredClone(next);return true;},candidates:async()=>{if(sourceFails)throw Error('source unavailable');return {candidates:fresh};},probe:async(ip,port)=>({ip,port,ok:latencies[ip]>=0,latency:latencies[ip]??-1})};
 const c=context();c.adapter=adapter;
 const m=new vm.SourceTextModule('const VERSION="2.6.0"; const CUSTOM_ADAPTER=adapter; const CUSTOM_UPSTREAM_WORKER={fetch:async()=>new Response("upstream"),scheduled:async()=>{}};\n'+runtime,{context:c});await m.link(()=>{});await m.evaluate();
 const worker=m.namespace.default;
 const call=async(extra={})=>{const res=await worker.fetch(new Request('https://example.test/_ops/bestip-refresh',{method:'POST',headers:{Authorization:'Bearer test-token'}}),{BESTIP_AUTO:'1',BESTIP_CRON_TOKEN:'test-token',BESTIP_POOL_SIZE:'2',...extra},{});return {status:res.status,body:await res.json()};};
 return {worker,call,writes:()=>writes,config:()=>cfg};
}
test('unauthorized refresh never probes or writes',async()=>{const t=await isolated();const r=await t.worker.fetch(new Request('https://example.test/_ops/bestip-refresh',{method:'POST'}),{BESTIP_CRON_TOKEN:'test-token'},{});assert.equal(r.status,404);assert.equal(t.writes(),0);});
test('unhealthy candidates preserve previous pool',async()=>{const old=[{ip:'old',port:443}];const t=await isolated({current:old,fresh:[{ip:'new'}]});assert.equal((await t.call()).body.data.status,'no-healthy-candidates');assert.deepEqual(t.config().preferredIPs,old);assert.equal(t.writes(),0);});
test('healthy old pool retains order within hysteresis and zero is honored',async()=>{const t=await isolated({current:[{ip:'old',port:443}],fresh:[{ip:'new',port:443}],latencies:{old:110,new:100}});const r=await t.call({BESTIP_POOL_SIZE:'1'});assert.equal(r.body.data.status,'unchanged');assert.equal(t.writes(),0);const n=await t.call({BESTIP_POOL_SIZE:'1',BESTIP_HYSTERESIS_MS:'0'});assert.equal(n.body.data.status,'updated');assert.equal(t.config().preferredIPs[0].ip,'new');assert.equal(t.config().admin,'retained');});
test('source failure can retain healthy current pool',async()=>{const t=await isolated({current:[{ip:'old',port:443}],sourceFails:true,latencies:{old:10}});assert.equal((await t.call()).body.data.status,'unchanged');assert.equal(t.writes(),0);});
test('missing KV reports failure rather than pretending a save succeeded',async()=>{const t=await isolated({fresh:[{ip:'new'}],latencies:{new:10},saveFails:true});const r=await t.call();assert.equal(r.status,500);assert.equal(r.body.ok,false);assert.equal(t.writes(),0);});
test('actual patched upstream worker loads and exposes identity and protected endpoint',async()=>{const c=context();const m=new vm.SourceTextModule(fs.readFileSync('CFNext 明文版.js','utf8'),{context:c});await m.link(spec=>{assert.equal(spec,'cloudflare:sockets');return new vm.SyntheticModule(['connect'],function(){this.setExport('connect',()=>{throw Error('network disabled');});},{context:c});});await m.evaluate();const w=m.namespace.default;const r=await w.fetch(new Request('https://example.test/version'),{},{});const version=parse(fs.readFileSync('CFNext 明文版.js','utf8'),{ecmaVersion:'latest',sourceType:'module'}).body.flatMap(n=>n.declarations||[]).find(n=>n.id.name==='VERSION').init.value;assert.deepEqual(await r.json(),{version,patchset:'stable-bestip-v2',repo:'wenxin1221-design/CFNext',upstream:'PAICNI/CFNext'});const n=await w.fetch(new Request('https://example.test/_ops/bestip-refresh',{method:'POST',headers:{Authorization:'Bearer x'}}),{BESTIP_CRON_TOKEN:'x'},{});assert.equal((await n.json()).data.status,'disabled');});
test('actual upstream adapters collect, probe and persist a fresh pool without losing config',async()=>{
 let cfg={uuid:'00000000-0000-4000-8000-000000000001',admin:'keep-admin',optimizer:{source:'custom',sourceURL:'https://source.test/ips',port:443,count:1,threads:1,useCidr:false},preferredIPs:[]};let writes=0;
 const c=context();c.fetch=async(url)=>{assert.equal(String(url),'https://source.test/ips');return new Response('203.0.113.2\n');};
 const m=new vm.SourceTextModule(fs.readFileSync('CFNext 明文版.js','utf8'),{context:c});
 await m.link(spec=>{assert.equal(spec,'cloudflare:sockets');return new vm.SyntheticModule(['connect'],function(){this.setExport('connect',()=>({opened:Promise.resolve(),close(){}}));},{context:c});});await m.evaluate();
 const env={BESTIP_AUTO:'1',BESTIP_CRON_TOKEN:'test-token',BESTIP_POOL_SIZE:'1',K:{get:async(key)=>key==='config'?JSON.stringify(cfg):null,put:async(key,value)=>{assert.equal(key,'config');writes++;cfg=JSON.parse(value);}}};
 const res=await m.namespace.default.fetch(new Request('https://example.test/_ops/bestip-refresh',{method:'POST',headers:{Authorization:'Bearer test-token'}}),env,{});
 assert.equal(res.status,200);const result=await res.json();assert.equal(result.data.status,'updated');assert.equal(writes,1);assert.equal(cfg.admin,'keep-admin');assert.deepEqual(cfg.preferredIPs,[{ip:'203.0.113.2',port:443,name:'CF-BEST-01'}]);
});
